/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * Determines if multiple selections are allowed
 */
export type Multiple = boolean;
/**
 * Determines if the select box is dense
 */
export type Density = "default" | "comfortable" | "compact";
/**
 * Determines if the select box is disabled
 */
export type Disabled = boolean;
/**
 * Changes the direction of the tabs. Can be either horizontal or vertical
 */
export type Direction = "horizontal" | "vertical";
/**
 * Color of the range slider. Can be custom or standard Material color
 */
export type Color = string | null;
/**
 * Trigger event for when to trigger a run
 */
export type Triggerevent = string;
/**
 * height of tab
 */
export type Height = string | number;
/**
 * Force v-tab to take up all available space
 */
export type Grow = boolean;
/**
 * Options for the select box. Can be a list of strings or integers
 */
export type Items = (string | number)[];
/**
 * align tabs
 */
export type AlignTabs = "start" | "title" | "center" | "end";
/**
 * Selected tab to be centered
 */
export type CenterActive = boolean;
/**
 * Selected options for tabs
 */
export type Value = (string | number)[] | string | number;
/**
 * List of child component ids to be placed within the tab
 */
export type Childcomponents = string[];

/**
 * Tabs component allows users to select from a list of options. Can be a single or multiple selection
 */
export interface Tabs {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  multiple?: Multiple;
  density?: Density;
  disabled?: Disabled;
  direction?: Direction;
  color?: Color;
  triggerEvent?: Triggerevent;
  height?: Height;
  grow?: Grow;
  items?: Items;
  align_tabs?: AlignTabs;
  center_active?: CenterActive;
  value?: Value;
  childComponents?: Childcomponents;
  [k: string]: unknown;
}
